# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('weight', models.FloatField(null=True)),
                ('price_per_unit', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('tax', models.FloatField(null=True)),
                ('type', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('location', models.CharField(default='Fremont', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceriesapp.Item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceriesapp.Store')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceriesapp.Store'),
        ),
    ]
