# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ManyToManyField(through='groceriesapp.Trip', to='groceriesapp.Store'),
        ),
    ]
