# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriesapp', '0003_auto_20170220_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='price',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='weight',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Snack', 'Snack'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Cosmetic', 'Cosmetic'), ('Kitchen Item', 'Kitchen Item'), ('Lentil', 'Lentil'), ('Grain', 'Grain'), ('Drink', 'Drink'), ('Dairy', 'Dairy'), ('Flour', 'Flour'), ('Chatni', 'Chatni'), ('Condiments', 'Condiments')], max_length=32, null=True),
        ),
    ]
